---
version: '3'
services:
  latex:
    container_name: projektarbeit_latex
    build:
      context: .
      dockerfile: Dockerfile
    image: my_latex:latest
    volumes:
      - ./:/src
    working_dir: /src
    command: "latexmk"
